name = "GraphTensorNetworks"
uuid = "0978c8c2-34f6-49c7-9826-ea2cc20dabd2"
authors = ["GiggleLiu <cacate0129@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
